framework:
    cache:
        app: cache.adapter.apcu
        system: cache.adapter.apcu
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            rate_limiter.cache:
                adapter: cache.adapter.redis
            validator.cache:
                adapter: cache.adapter.apcu
            doctrine.result_cache_pool:
                adapter: cache.adapter.apcu
            doctrine.system_cache_pool:
                adapter: cache.adapter.apcu
