FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2

#ADD docker/logstash/supervisor/ /etc/supervisor/conf.d/
ADD docker/logstash/conf.d/ /etc/logstash/conf.d/
ADD docker/logstash/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENTRYPOINT ["sh", "/usr/bin/docker-entrypoint.sh"]
